# Generated by Django 6.0 on 2026-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='item_code',
            field=models.CharField(default='ABC-1', help_text='HS Code / eTIMS Item Code', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='tax_type',
            field=models.CharField(choices=[('A', '16% VAT (Standard)'), ('B', '0% VAT (Zero-rated)'), ('C', 'Exempt')], default='A', max_length=2),
        ),
    ]
