# Generated by Django 6.0 on 2026-03-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variant_item_code_variant_tax_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
