# Generated by Django 6.0 on 2026-04-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage_variantimage'),
    ]

    operations = [
    ]
