# Generated by Django 6.0.5 on 2026-05-27 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimage_image_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variantimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='error_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='last_optimized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='optimization_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='productimage',
            name='optimized_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='raw_external_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='error_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='last_optimized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='optimization_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='optimized_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='raw_external_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
