# Generated by Django 6.0.5 on 2026-06-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productimage_image_remove_variantimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='optimized_images/'),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='optimized_images/'),
        ),
    ]
