# Generated by Django 6.0.5 on 2026-06-27 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productimage_local_image_variantimage_local_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'name'], name='products_ca_parent__8c0bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-id'], name='products_pr_is_acti_6072ca_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['inventory', '-created_at'], name='products_st_invento_e49911_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['user', '-created_at'], name='products_st_user_id_4d7ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='products_st_movemen_b0ca0a_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', 'sku'], name='products_va_product_466ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['sku'], name='products_va_sku_5451be_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', 'price'], name='products_va_product_a09df2_idx'),
        ),
    ]
