# Generated by Django 6.0.5 on 2026-09-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='raw_storage_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='raw_storage_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
