# Generated by Django 6.0 on 2026-03-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash Office'), ('MPESA', 'M-Pesa Paybill'), ('BANK', 'Bank Account'), ('REVENUE', 'Sales Revenue'), ('EXPENSE', 'Expenses/Purchases')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Money In'), ('OUT', 'Money Out')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('SALES', 'Sales Payment'), ('DEPOSIT', 'Cash Deposit'), ('WITHDRAWAL', 'Cash Withdrawal'), ('REFUND', 'Refund'), ('EXPENSE', 'Expense Payment'), ('PURCHASE', 'Purchase Payment')], default='SALES', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='M-Pesa Receipt, Cash Receipt No, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='payments.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.transaction')),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='orders.order')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_cash_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Transaction',
            },
            bases=('payments.transaction',),
        ),
        migrations.CreateModel(
            name='DepositWithdrawal',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.transaction')),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='payments.account')),
            ],
            options={
                'verbose_name': 'Deposit / Withdrawal',
            },
            bases=('payments.transaction',),
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.transaction')),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('SUPPLIES', 'Supplies'), ('UTILITIES', 'Utilities'), ('SALARY', 'Salary'), ('RENT', 'Rent'), ('OTHER', 'Other')], max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Transaction',
            },
            bases=('payments.transaction',),
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.transaction')),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='orders.order')),
            ],
            options={
                'verbose_name': ' M-Pesa Transaction',
            },
            bases=('payments.transaction',),
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.transaction')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Sale Transaction',
            },
            bases=('payments.transaction',),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'timestamp'], name='payments_tr_user_id_e832ed_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'timestamp'], name='payments_tr_account_c0cdac_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'timestamp'], name='payments_tr_transac_206fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_id'], name='payments_tr_referen_91e1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='payments_mp_checkou_a6f836_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['mpesa_receipt_number'], name='payments_mp_mpesa_r_3e414a_idx'),
        ),
    ]
