# Generated by Django 6.0 on 2026-01-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
    ]
