# Generated by Django 6.0 on 2026-01-26 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_cashtransaction_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash Office'), ('MPESA', 'M-Pesa Paybill'), ('BANK', 'Bank Account'), ('REVENUE', 'Sales Revenue'), ('EXPENSE', 'Expenses/Purchases')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Money In'), ('OUT', 'Money Out')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALES', 'Sales Payment'), ('DEPOSIT', 'Cash Deposit'), ('WITHDRAWAL', 'Cash Withdrawal'), ('REFUND', 'Refund'), ('EXPENSE', 'Expense Payment'), ('PURCHASE', 'Purchase Payment')], default='SALES', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='payments.account'),
        ),
    ]
