# Generated by Django 6.0 on 2026-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_mpesatransaction_bill_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
