# Generated by Django 6.0 on 2026-01-26 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0003_account_alter_transaction_movement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='orders.order'),
            preserve_default=False,
        ),
    ]
