# Generated by Django 6.0.5 on 2026-05-26 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
        ('payments', '0004_remove_mpesatransaction_status_transaction_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.transaction')),
                ('access_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Paystack Transaction',
                'indexes': [models.Index(fields=['paystack_reference'], name='payments_pa_paystac_a1ecea_idx')],
            },
            bases=('payments.transaction',),
        ),
    ]
