# Generated by Django 6.0 on 2025-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fix_outstandingtoken_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Kenyan phone for M-Pesa/OTP', max_length=15, unique=True),
        ),
    ]
