# Generated by Django 6.0 on 2025-12-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_email_unique'),
        ('users', '0004_alter_user_email'),
    ]

    operations = [
    ]
