# Generated by Django 6.0.5 on 2026-09-07 23:48

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_users_user_email_6f2530_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
