# Generated by Django 6.0.5 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=255, unique=True)),
                ('recipient', models.CharField(max_length=32)),
                ('intent', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(default='PENDING', max_length=64)),
                ('network_code', models.CharField(blank=True, max_length=32)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('delivery_reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['provider_message_id'], name='users_smsn_provide_b3634a_idx'),
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['status'], name='users_smsn_status_f725d4_idx'),
        ),
    ]
