# Generated by Django 6.0.5 on 2026-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_smsnotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='smsnotification',
            new_name='users_smsno_provide_30ee37_idx',
            old_name='users_smsn_provide_b3634a_idx',
        ),
        migrations.RenameIndex(
            model_name='smsnotification',
            new_name='users_smsno_status_bbccab_idx',
            old_name='users_smsn_status_f725d4_idx',
        ),
    ]
