# production.py
"""
Django settings for homepointBackend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import ssl
import dj_database_url
from urllib.parse import urlparse
from .base import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


# If deploying on Railway, dynamically append the public domain if set
RAILWAY_PUBLIC_DOMAIN = os.environ.get("RAILWAY_PUBLIC_DOMAIN")
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)


# Get env var string (e.g., "https://homepoint-pi.vercel.app")
CORS_ENV = os.environ.get("CORS_ALLOWED_ORIGINS", "")

# Clean and split into a list
if CORS_ENV:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ENV.split(",") if origin.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
    ]

# Explicitly allow Vercel origins
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/.*\.vercel\.app$",
]

# Ensure preflight OPTIONS requests pass without authentication checks
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_CREDENTIALS = True



# Trust Fly.io proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# SSL/TLS
SECURE_SSL_REDIRECT = False #True
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Session cookies
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True
# Fetch the raw string from environment
raw_csrf = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
# Convert comma-separated string into a clean list of origins
if raw_csrf:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in raw_csrf.split(",") if origin.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []

# Other security
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'


USE_AWS = config('USE_AWS', default=False, cast=bool)

if USE_AWS:
    # AWS Authentication Keys
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
    
    # Optional: If using CloudFront to speed up asset delivery, add its URL here
    AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL', default=None)
    AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default=f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com")
    CLOUDFRONT_DOMAIN = AWS_S3_CUSTOM_DOMAIN
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_QUERYSTRING_AUTH = config('AWS_QUERYSTRING_AUTH', default=True, cast=bool)
    
    # S3 Performance Optimizations
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400', # Tell browsers to cache static files for 1 day
    }
    AWS_DEFAULT_ACL = None # Rely on S3 bucket policies instead of ACLs

    # Static files settings
    STATIC_LOCATION = 'static'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN or f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"}/{STATIC_LOCATION}/'
    
    # Media files settings
    MEDIA_LOCATION = 'media'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN or f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"}/{MEDIA_LOCATION}/'

    S3_OPTIONS = {
        "access_key": AWS_ACCESS_KEY_ID,
        "secret_key": AWS_SECRET_ACCESS_KEY,
        "bucket_name": AWS_STORAGE_BUCKET_NAME,
        "endpoint_url": AWS_S3_ENDPOINT_URL,
        "signature_version": AWS_S3_SIGNATURE_VERSION,
        "region_name": AWS_S3_REGION_NAME,
        "querystring_auth": AWS_QUERYSTRING_AUTH,
        "addressing_style": "virtual",  # Critical for custom S3 compatibility
    }

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                **S3_OPTIONS,
                "location": MEDIA_LOCATION,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                **S3_OPTIONS,
                "location": STATIC_LOCATION,
            },
        },
    }
        
else:

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Cache Configuration
redis_url = os.environ.get('REDIS_URL')
parsed = urlparse(redis_url)
use_tls = parsed.scheme == 'rediss'

if not redis_url and os.environ.get('DB_HOST') == 'db':
    # We are likely running in Docker where the redis container is available
    redis_url = 'redis://redis:6379/1'

if redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': redis_url,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

'''
CELERY_BROKER_USE_SSL = {
    'ssl_cert_reqs': ssl.CERT_NONE,  # Upstash uses self-signed
    'ssl_ca_certs': None,
}
CELERY_REDIS_BACKEND_USE_SSL = CELERY_BROKER_USE_SSL
'''



# Logging
'''
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            'class': 'pythonjsonlogger.json.JsonFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('LOG_LEVEL', 'INFO'),
    },
}'''
