<template>
  <div class="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-3xl mx-auto bg-white p-8 shadow rounded-lg prose prose-indigo">
      <h1>Privacy Policy</h1>
      <p>Last updated: May 26, 2026</p>
      <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
      <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank">Privacy Policy Generator</a>.</p>
      
      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
      
      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Homepoint POS.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>Country</strong> refers to: Kenya</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
        <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>Website</strong> refers to Homepoint POS, accessible from <a href="https://betasys.co.ke" rel="external nofollow noopener" target="_blank">https://betasys.co.ke</a>.</li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>
      <h3>Types of Data Collected</h3>
      <h4>Personal Data</h4>
      <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
      </ul>

      <h4>Usage Data</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
      <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
      <p>We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>

      <h4>Tracking Technologies and Cookies</h4>
      <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
      <ul>
        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
      </ul>
      <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
      <p>Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.</p>
      <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
      <ul>
        <li><strong>Necessary / Essential Cookies</strong> (Session Cookies): Administered by Us. Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</li>
        <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> (Persistent Cookies): Administered by Us. Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
        <li><strong>Functionality Cookies</strong> (Persistent Cookies): Administered by Us. Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
      </ul>

      <h3>Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>To provide and maintain our Service, manage Your Account, performance of a contract, contact You, provide news/offers, manage requests, business transfers, and other purposes.</li>
      </ul>

      <h3>Retention of Your Personal Data</h3>
      <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Account information is retained for up to 24 months after account closure. Website analytics and server logs are also retained for up to 24 months.</p>

      <h3>Transfer of Your Personal Data</h3>
      <p>Your information may be transferred to and maintained on computers located outside of Your jurisdiction. We ensure appropriate safeguards are in place for such transfers.</p>

      <h3>Delete Your Personal Data</h3>
      <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>

      <h3>Disclosure of Your Personal Data</h3>
      <p>We may disclose Your Personal Data for business transactions, law enforcement, or other legal requirements.</p>

      <h3>Security of Your Personal Data</h3>
      <p>No method of transmission or storage is 100% secure, but We strive to use commercially reasonable means to protect Your Personal Data.</p>

      <h2>Children's Privacy</h2>
      <p>Our Service does not address anyone under the age of 16. We do not knowingly collect information from children under 16.</p>

      <h2>Links to Other Websites</h2>
      <p>Our Service may contain links to other websites. We advise You to review the Privacy Policy of every site You visit.</p>

      <h2>Changes to this Privacy Policy</h2>
      <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>

      <h2>Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul>
        <li>By email: ken.mwangi.kinyua81@gmail.com</li>
        <li>By phone: +254743705910</li>
      </ul>

      <div class="mt-8 pt-8 border-t">
        <router-link to="/register" class="text-indigo-600 hover:text-indigo-500 font-medium">
          &larr; Back to Registration
        </router-link>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for a static policy page
</script>

<style scoped>
/* Basic prose-like styling using standard CSS to avoid build issues */
.prose h1 { 
  font-size: 1.875rem; 
  line-height: 2.25rem; 
  font-weight: 700; 
  margin-bottom: 1.5rem; 
}
.prose h2 { 
  font-size: 1.5rem; 
  line-height: 2rem; 
  font-weight: 600; 
  margin-top: 2rem; 
  margin-bottom: 1rem; 
}
.prose h3 { 
  font-size: 1.25rem; 
  line-height: 1.75rem; 
  font-weight: 500; 
  margin-top: 1.5rem; 
  margin-bottom: 0.5rem; 
}
.prose p { 
  margin-bottom: 1rem; 
  line-height: 1.625; 
}
.prose ul { 
  list-style-type: disc; 
  margin-left: 1.5rem; 
  margin-bottom: 1rem; 
}
.prose li { 
  margin-bottom: 0.5rem; 
}
.prose strong { 
  font-weight: 600; 
}
</style>
