# Generated by Django 6.0 on 2026-03-18 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_mpesatransaction_bill_reference_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('mpesa_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mpesa_count', models.IntegerField(default=0)),
                ('cash_count', models.IntegerField(default=0)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mpesa_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Sales Snapshot',
                'verbose_name_plural': 'Daily Sales Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY_SALES', 'Daily Sales Summary'), ('PERIOD_SALES', 'Period Sales Report'), ('PAYMENT_METHOD', 'Payment Method Breakdown'), ('CASH_FLOW', 'Cash Flow Statement'), ('MPESA_RECONCILIATION', 'M-Pesa Reconciliation'), ('ACCOUNT_LEDGER', 'Account Ledger'), ('USER_PERFORMANCE', 'User Performance Report'), ('PRODUCT_SALES', 'Product Sales Analysis'), ('TAX_REPORT', 'Tax Report (VAT)')], max_length=30)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=True)),
                ('email_subject_template', models.CharField(blank=True, max_length=255)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipients', models.ManyToManyField(related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='AccountReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_type', models.CharField(choices=[('MPESA', 'M-Pesa Reconciliation'), ('BANK', 'Bank Reconciliation'), ('CASH', 'Cash Count Reconciliation')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('expected_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('DISCREPANCY', 'Discrepancy Found'), ('PENDING', 'Pending Review'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='payments.account')),
                ('reconciled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reconciled_at'],
                'indexes': [models.Index(fields=['account', '-reconciled_at'], name='reports_acc_account_aa9f95_idx'), models.Index(fields=['status'], name='reports_acc_status_705c4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('TRANSACTION_CREATED', 'Transaction Created'), ('TRANSACTION_MODIFIED', 'Transaction Modified'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('ACCOUNT_ADJUSTED', 'Account Balance Adjusted'), ('REPORT_GENERATED', 'Report Generated'), ('RECONCILIATION_PERFORMED', 'Reconciliation Performed')], max_length=30)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='reports_aud_model_n_dc47ea_idx'), models.Index(fields=['user', '-timestamp'], name='reports_aud_user_id_109722_idx'), models.Index(fields=['action_type', '-timestamp'], name='reports_aud_action__d531de_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY_SALES', 'Daily Sales Summary'), ('PERIOD_SALES', 'Period Sales Report'), ('PAYMENT_METHOD', 'Payment Method Breakdown'), ('CASH_FLOW', 'Cash Flow Statement'), ('MPESA_RECONCILIATION', 'M-Pesa Reconciliation'), ('ACCOUNT_LEDGER', 'Account Ledger'), ('USER_PERFORMANCE', 'User Performance Report'), ('PRODUCT_SALES', 'Product Sales Analysis'), ('TAX_REPORT', 'Tax Report (VAT)')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_transactions', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', '-generated_at'], name='reports_rep_report__a7c87c_idx'), models.Index(fields=['generated_by', '-generated_at'], name='reports_rep_generat_c7e29e_idx'), models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_29aaa5_idx')],
            },
        ),
    ]
