# Generated by Django 6.0.5 on 2026-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reporthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('DAILY_SALES', 'Daily Sales Summary'), ('PERIOD_SALES', 'Period Sales Report'), ('PAYMENT_METHOD', 'Payment Method Breakdown'), ('CASH_FLOW', 'Cash Flow Statement'), ('MPESA_RECONCILIATION', 'M-Pesa Reconciliation'), ('PAYSTACK_RECONCILIATION', 'Paystack Reconciliation'), ('ACCOUNT_LEDGER', 'Account Ledger'), ('USER_PERFORMANCE', 'User Performance Report'), ('PRODUCT_SALES', 'Product Sales Analysis'), ('TAX_REPORT', 'Tax Report (VAT)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(choices=[('DAILY_SALES', 'Daily Sales Summary'), ('PERIOD_SALES', 'Period Sales Report'), ('PAYMENT_METHOD', 'Payment Method Breakdown'), ('CASH_FLOW', 'Cash Flow Statement'), ('MPESA_RECONCILIATION', 'M-Pesa Reconciliation'), ('PAYSTACK_RECONCILIATION', 'Paystack Reconciliation'), ('ACCOUNT_LEDGER', 'Account Ledger'), ('USER_PERFORMANCE', 'User Performance Report'), ('PRODUCT_SALES', 'Product Sales Analysis'), ('TAX_REPORT', 'Tax Report (VAT)')], max_length=30),
        ),
    ]
